### ISSUE TITLE
Make this for angular

### ISSUE THREAD

**Issue by gsaggu** [sukhvir41/HtmlTemplate#2]
thanks

**Comment by surajgoraya** [comment]
This is a great suggestion @gsaggu. @sukhvir41 Please consider this.

**Comment by gsaggu** [comment]
@sukhvir41 its incomplete, why you closed it

**Comment by ThomasAR** [comment]
@gsaggu @surajgoraya I think your suggestion is great. If the developer deletes his entire codebase and remakes it for use with superior technology, I believe he would see a huge spike in popularity. We should fork and begin work on issue #1 at our earliest convenience.

We should also be sure to maintain the same coding philosophy as the original developer while completing this issue, pictured below.
![image](https://user-images.githubusercontent.com/14037175/87822075-de389880-c83e-11ea-97ce-f82b12da8594.png)
